/* trigger para KARDEX*/ 
CREATE OR REPLACE TRIGGER tri_del_tabla AFTER DELETE ON tab_kardex
FOR EACH ROW EXECUTE PROCEDURE fun_del_tablasKARDEX();

CREATE OR REPLACE TRIGGER tri_INSERTKARDEX_tabla AFTER INSERT  ON tab_kardex
FOR EACH ROW EXECUTE PROCEDURE fun_del_tablasKARDEX();

CREATE OR REPLACE  TRIGGER tri_act_tabla BEFORE INSERT OR UPDATE ON tab_kardex
FOR EACH ROW EXECUTE PROCEDURE fun_act_tabla();